shallow_clone: true
version: "Build {build}"

os:
#  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

build:
  parallel: true
  verbosity: quiet # MSBuild verbosity level (quiet|minimal|normal|detailed)

skip_commits:
  message: /\[[aA]ppveyor [sS]kip\]/

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\boomerang

branches:
  except:
    - gh-pages

pull_requests:
  do_not_increment_build_number: true

before_build:
  - ps: cd C:\projects\boomerang
  - ps: mkdir build
  - ps: cd build
  - ps: ..\scripts\appveyor-generate.ps1

matrix:
  fast_finish: true

build_script:
    - cmake --build .
    - cmake --build . --target PACKAGE

test_script:
    - cmake --build . --target RUN_TESTS

