#
# This file is part of the Boomerang Decompiler.
#
# See the file "LICENSE.TERMS" for information on usage and
# redistribution of this file, and for a DISCLAIMER OF ALL
# WARRANTIES.
#

version: "Build {build}"

os:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

branches:
  except:
    - gh-pages

skip_commits:
  message: /\[[aA]ppveyor [sS]kip\]/

cache: c:\tools\vcpkg\installed\

clone_folder: C:\projects\boomerang

build:
  parallel: true
  verbosity: quiet # MSBuild verbosity level (quiet|minimal|normal|detailed)

matrix:
  fast_finish: true

pull_requests:
  do_not_increment_build_number: true

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cd C:\Tools\vcpkg
  - git pull
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  - ps: cd C:\projects\boomerang
  - ps: mkdir build
  - ps: cd build
  - ps: ..\scripts\appveyor-generate.ps1

build_script:
  - cmake --build . --target PACKAGE # this includes ALL

test_script:
  - cmake --build . --target RUN_TESTS

artifacts:
  - path: 'build\boomerang-*.exe'
    name: Installer
    type: File
  - path: 'build\boomerang-*.zip'
    name: Portable ZIP
    type: File
